# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Button_link.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(810, 609)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(490, 30, 61, 31))
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(40, 30, 261, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "选择您需要展示的曲线（可多选）")
        self.comboBox.addItem("")
        self.comboBox.setItemText(1, "曲线1")
        self.comboBox.addItem("")
        self.comboBox.setItemText(2, "曲线2")
        self.comboBox.addItem("")
        self.comboBox.setItemText(3, "曲线3")
        self.graphicsView = QtWidgets.QGraphicsView(Form)
        self.graphicsView.setGeometry(QtCore.QRect(70, 160, 641, 411))
        self.graphicsView.setObjectName("graphicsView")
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setGeometry(QtCore.QRect(110, 70, 91, 19))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(Form)
        self.checkBox_2.setGeometry(QtCore.QRect(110, 100, 91, 19))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(Form)
        self.checkBox_3.setGeometry(QtCore.QRect(110, 130, 91, 19))
        self.checkBox_3.setObjectName("checkBox_3")

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.feedback)
        self.checkBox_2.clicked.connect(Form.select2)
        self.checkBox_3.clicked.connect(Form.select3)
        self.checkBox.clicked.connect(Form.select1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "画图"))
        self.checkBox.setText(_translate("Form", "曲线1"))
        self.checkBox_2.setText(_translate("Form", "曲线2"))
        self.checkBox_3.setText(_translate("Form", "曲线3"))
